# Generated by Django 2.0.7 on 2018-08-31 09:01

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields
import sberbank.models


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank', '0004_logentry_request_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-updated'], 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.CharField(db_index=True, max_length=100, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='bank_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='банковский ИД платежа'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='payment_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ИД платежа'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='request_text',
            field=models.TextField(blank=True, null=True, verbose_name='текст запроса'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='response_text',
            field=models.TextField(blank=True, null=True, verbose_name='текст ответа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=128, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client_id',
            field=models.TextField(blank=True, null=True, verbose_name='код клиента'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True, verbose_name='детали'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='error_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='код ошибки'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='текст ошибки'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'CREATED'), (1, 'PENDING'), (2, 'SUCCEEDED'), (3, 'FAILED')], db_index=True, default=sberbank.models.Status(0), verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='обновлен'),
        ),
    ]
