# Generated by Django 2.0.13 on 2020-11-18 08:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sberbank', '0008_payment_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='details',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='details'),
        ),
    ]
